### ISSUE TITLE
Länge des Titels

### ISSUE THREAD

**Issue by usauerbrey** [jansauerbrey/recipe-app#11]
Der Titel wird in der Übersicht abgeschnitten:
"Avocado-Toastie mit getrockneten Tomaten - unferti"
Wenn das nötig ist, muss dass schon bei der Eingabe angezeigt werden

**Comment by jansauerbrey** [comment]
Muss es bei der Eingabe bereits angezeigt werden, da der name ja weiterhin so lang sein darf und auch im Rezept angezeigt wird, oder reicht es wenn ich z.B. durch "..." kenntlich mache, dass der Name noch weiter geht?

**Comment by jansauerbrey** [comment]
jetztwird der komplette name angezeigt, oder mit ... abgeschnitten. Hoffe das hilft.
